import type { Metadata } from "next";
import { Geist, Geist_Mono,Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Marquee from "@/components/Marquee";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const notoSerifBengali = Noto_Serif_Bengali({
 
  subsets: ["latin",'bengali'],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
    data-theme = 'light'
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <Marquee></Marquee>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
